GET http://localhost:3000/user

###
POST http://localhost:3000/user
Content-Type: application/json

{
    "name": "Michael Nascimento",
    "email": "teste@teste.com",
    "accountId": 1
}

###
GET http://localhost:3000/account


###
POST http://localhost:3000/account
Content-Type: application/json

{
    "companyName": "Empresa Teste"
}